# 保存为utf-8格式
spring:
  profiles:
    active: dev

---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: config-provider-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.199.132:3306/cloudDB01
    username: root
    password: root

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jcfc.springcloud.entity

eureka:
  instance:
    prefer-ip-address: true   #访问路径可以显示IP地址
    instance-id: config-provider-8001  #自定义服务实例名称
  client:
      service-url:
        defaultZone: http://localhost:7001/eureka/

---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: config-provider-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.199.132:3306/cloudDB02
    username: root
    password: root

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jcfc.springcloud.entity

eureka:
  instance:
    prefer-ip-address: true   #访问路径可以显示IP地址
    instance-id: config-provider-8002  #自定义服务实例名称
  client:
      service-url:
        defaultZone: http://localhost:7001/eureka/