server:
  port: 8001

spring:
  application:
    name: provider-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.199.131:3306/cloudDB01
    username: root
    password: root

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jcfc.springcloud.entity
  # config-location 和 configuration不能同时存在，需要在配置文件中配置驼峰匹配
  #configuration:
    #map-underscore-to-camel-case: true
